name: Deploy to Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: "Install dependencies"
        run: yarn install

      - name: "Decrypt env file"
        run: npx senv decrypt .env.staging.encrypted > .env -p ${{ secrets.DOTENV_PASSWORD }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LUNA_SSH_HOST }}
          username: ${{ secrets.LUNA_SSH_USERNAME }}
          key: ${{ secrets.LUNA_SSH_KEY }}
          port: ${{ secrets.LUNA_SSH_PORT }}
          passphrase: ${{ secrets.LUNA_SSH_PASSPHRASE }}
          source: "*"
          target: "${{ secrets.STAGING_SERVER_FOLDER }}/releases/${{ github.sha }}"

      - name: Update Symlink and remove old releases
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.LUNA_SSH_HOST }}
          USERNAME: ${{ secrets.LUNA_SSH_USERNAME }}
          PORT: ${{ secrets.LUNA_SSH_PORT }}
          KEY: ${{ secrets.LUNA_SSH_KEY }}
          PASSPHRASE: ${{ secrets.LUNA_SSH_PASSPHRASE }}
          script: |
            rm -rf ${{ secrets.STAGING_SERVER_FOLDER }}/public_html
            ln -sfn ${{ secrets.STAGING_SERVER_FOLDER }}/releases/${{ github.sha }} ${{ secrets.STAGING_SERVER_FOLDER }}/public_html
            cd ${{ secrets.STAGING_SERVER_FOLDER }}/releases && ls -1tr | head -n -2 | xargs rm -rf
